### ISSUE TITLE
Créer des fichiers .php pour les différentes sections de l'espace membre. 

### ISSUE THREAD

**Issue by philippesimard** [philippesimard/vivelepartage#1]
Salut, 

Il faudrait créer des fichiers PHP pour les différentes sections de l'espace membre.  L'ensemble se trouvera dans un dossier nommé account.

Ex. Mes emprunts, paramètres, proposer un object, etc. 

Merci 

Philippe

**Comment by jlagab** [comment]
[membre.zip](https://github.com/philippesimard/vivelepartage/files/298407/membre.zip)
 genre comme ça ?

**Comment by jlagab** [comment]
je viens de voir qu'il y en avait déjà créés dans la section code, du coup je comprends pas ce que tu demandais ?

**Comment by jlagab** [comment]
okay je crois que j'ai compris, j'ai créé un sous-répertoire  avec les fichiers ;-)
